### ISSUE TITLE
HTTP method

### ISSUE THREAD

**Issue by mynolog** [fatejin/website_project#1]
website_project/webdrill/js/ui.js : line 35

```javascript
$.ajax({
	type: 'post', //HTTP 요청 방식
	url: liurl, //해당 url
	dataType: 'html', //data 타입
	success: function (data) { //HTTP 요청 성공 후 데이터 전송
		$(".notebook").html(data);
	}
});
```

```javascript
$.ajax({
	type: 'get', //HTTP 요청 방식을 post가 아닌 get으로 변경
	url: liurl, //해당 url
	dataType: 'html', //data 타입
	success: function (data) { //HTTP 요청 성공 후 데이터 전송
		$(".notebook").html(data);
	}
});
```

추가로 404 에러는 favicon 파일이 없어서 발생하는 에러로 해당 코드의 내용과는 무관하기 때문에 신경 안쓰셔도 되고
http 메소드 문제였네요. 자세한 내용은 직접 찾아보시는게 도움이 될 거 같아서 언급하진 않겠습니다.
HTTP method로 검색해보시면 관련 내용 나올거에요 :)

**Comment by fatejin** [comment]
성공했습니다. 정말 기분이 기쁩니다. 감사합니다. POST 와 GET의 차이가 궁금했는데 이제 이해가 갑니다.ㅎㅎ

2021년 1월 25일 (월) 오후 5:48, Minho Lee <notifications@github.com>님이 작성:
